nelmio_api_doc:
    documentation:
        info:
            title: Word popularity app
            description: Get scores of the words based on the positive and negative connotation.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc.json$) # Accepts routes under /api except /api/doc
